# ============================================================
# Telecom Customer Analytics Platform
# Generalized Data Profiling Notebook — All Datasets
# ============================================================
# Datasets:
#   1. pk.csv              — Pakistan Cities (Geographic Reference)
#   2. WA_Fn-UseC_-Telco-Customer-Churn.csv — IBM Telco Churn (Original)
#   3. Telco_customer_churn.xlsx            — IBM Telco Churn (Extended)
#   4. 410.csv             — OpenCelliD Cell Tower Data (Pakistan MCC=410)
# ============================================================

## Phase 1 — Import Libraries & Global Configuration

In [20]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os
from pathlib import Path
from datetime import datetime

warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)
pd.set_option('display.float_format', '{:.4f}'.format)

# ── Output Folders ──────────────────────────────────────────
OUTPUT_DIR  = Path('profiling_outputs')
PLOTS_DIR   = OUTPUT_DIR / 'plots'
RESULTS_DIR = OUTPUT_DIR / 'results'

for d in [OUTPUT_DIR, PLOTS_DIR, RESULTS_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ── Color Palette ────────────────────────────────────────────
PALETTE = ['#2196F3', '#FF5722', '#4CAF50', '#9C27B0',
           '#FF9800', '#00BCD4', '#E91E63', '#607D8B']

print('Libraries loaded. Outputs will be saved to:', OUTPUT_DIR.resolve())

Libraries loaded. Outputs will be saved to: D:\telecom-customer-analytics-platform\notebooks\profiling_outputs

## Phase 2 — Generalized Profiling Engine

In [21]:
# ============================================================
# GENERALIZED PROFILING FUNCTIONS
# ============================================================

# ── Master results store (accumulates across all datasets) ───
MASTER_RESULTS = {}


# ── 1. Dataset Overview ──────────────────────────────────────
def overview(df, name):
    """Rows, columns, memory usage."""
    mem_mb = df.memory_usage(deep=True).sum() / 1024**2
    info = {
        'rows':    df.shape[0],
        'columns': df.shape[1],
        'memory_mb': round(mem_mb, 4)
    }
    print(f"\n{'='*60}")
    print(f"  DATASET OVERVIEW — {name}")
    print(f"{'='*60}")
    print(f"  Rows               : {info['rows']:,}")
    print(f"  Columns            : {info['columns']}")
    print(f"  Memory Usage (MB)  : {info['memory_mb']}")
    return info


# ── 2. Column Names ──────────────────────────────────────────
def column_names(df, name):
    """Print and return all column names."""
    print(f"\n{'='*60}")
    print(f"  COLUMN NAMES — {name}")
    print(f"{'='*60}")
    cols = list(df.columns)
    for i, c in enumerate(cols, 1):
        print(f"  {i:3}. {c}")
    return cols


# ── 3. Data Types ────────────────────────────────────────────
def data_types(df, name):
    """Return a DataFrame of column → dtype."""
    dtype_df = pd.DataFrame({
        'Column': df.columns,
        'DType':  df.dtypes.astype(str).values
    })
    print(f"\n{'='*60}")
    print(f"  DATA TYPES — {name}")
    print(f"{'='*60}")
    print(dtype_df.to_string(index=False))
    return dtype_df


# ── 4. Summary Statistics ────────────────────────────────────
def summary_statistics(df, name):
    """describe() on numeric + object columns."""
    print(f"\n{'='*60}")
    print(f"  SUMMARY STATISTICS — {name}")
    print(f"{'='*60}")
    numeric_desc = df.describe(include=[np.number])
    object_desc  = df.describe(include=['object'])
    print("\n[Numeric]")
    print(numeric_desc)
    if not object_desc.empty:
        print("\n[Categorical]")
        print(object_desc)
    return numeric_desc, object_desc


# ── 5. Duplicate Rows ────────────────────────────────────────
def duplicate_analysis(df, name, id_col=None):
    """Count duplicate rows and optionally duplicate ID values."""
    total_dups = df.duplicated().sum()
    dup_pct    = round(total_dups / len(df) * 100, 2)
    result = {'total_duplicate_rows': int(total_dups),
              'duplicate_pct': dup_pct}
    print(f"\n{'='*60}")
    print(f"  DUPLICATE ANALYSIS — {name}")
    print(f"{'='*60}")
    print(f"  Duplicate Rows       : {total_dups}")
    print(f"  Duplicate Percentage : {dup_pct:.2f}%")
    if id_col and id_col in df.columns:
        id_dups = df[id_col].duplicated().sum()
        result['duplicate_id_col'] = id_col
        result['duplicate_id_count'] = int(id_dups)
        print(f"  Duplicate '{id_col}'     : {id_dups}")
    return result


# ── 6. Missing Values ────────────────────────────────────────
def missing_values(df, name):
    """Count and percentage of NaN per column."""
    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)
    mv_df = pd.DataFrame({
        'Missing_Count': missing,
        'Missing_Pct':   missing_pct
    }).sort_values('Missing_Count', ascending=False)
    print(f"\n{'='*60}")
    print(f"  MISSING VALUES — {name}")
    print(f"{'='*60}")
    with_missing = mv_df[mv_df['Missing_Count'] > 0]
    if with_missing.empty:
        print("  No missing values found.")
    else:
        print(with_missing.to_string())
    total_mv = int(missing.sum())
    print(f"\n  Total Missing Cells  : {total_mv}")
    print(f"  Total Cells          : {df.shape[0] * df.shape[1]}")
    return mv_df


# ── 7. Blank / Whitespace Values ─────────────────────────────
def blank_whitespace(df, name, extra_cols=None):
    """Detect empty strings in object + specified columns."""
    print(f"\n{'='*60}")
    print(f"  BLANK / WHITESPACE VALUES — {name}")
    print(f"{'='*60}")
    obj_cols = list(df.select_dtypes(include='object').columns)
    if extra_cols:
        obj_cols = list(set(obj_cols + extra_cols))
    blank_summary = {}
    for col in obj_cols:
        if col in df.columns:
            blank_count = df[col].astype(str).str.strip().eq('').sum()
            if blank_count > 0:
                blank_summary[col] = blank_count
                print(f"  {col:<30}: {blank_count} blank values")
    if not blank_summary:
        print("  No blank/whitespace values found.")
    return blank_summary


# ── 8. Unique Values ────────────────────────────────────────
def unique_values(df, name):
    """Count distinct values per column."""
    uv_df = pd.DataFrame({
        'Column':        df.columns,
        'Unique_Count':  df.nunique().values,
        'Total_Count':   len(df),
        'Unique_Pct':    (df.nunique() / len(df) * 100).round(2).values
    })
    print(f"\n{'='*60}")
    print(f"  UNIQUE VALUES — {name}")
    print(f"{'='*60}")
    print(uv_df.to_string(index=False))
    return uv_df


# ── 9. Cardinality ──────────────────────────────────────────
def cardinality(df, name, low_thresh=5, med_thresh=20):
    """Classify each column as Low / Medium / High cardinality."""
    def classify(n):
        if n <= low_thresh:  return 'Low'
        if n <= med_thresh:  return 'Medium'
        return 'High'
    card_df = pd.DataFrame({
        'Column':      df.columns,
        'Unique':      df.nunique().values,
        'Cardinality': [classify(n) for n in df.nunique().values]
    })
    print(f"\n{'='*60}")
    print(f"  CARDINALITY — {name}")
    print(f"{'='*60}")
    print(card_df.to_string(index=False))
    return card_df


# ── 10. Numeric Columns ─────────────────────────────────────
def numeric_columns(df, name):
    """Auto-detect and list numeric columns."""
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    print(f"\n{'='*60}")
    print(f"  NUMERIC COLUMNS — {name}")
    print(f"{'='*60}")
    for c in num_cols:
        print(f"  {c:<30} {str(df[c].dtype):<12}")
    print(f"\n  Total Numeric Columns : {len(num_cols)}")
    return num_cols


# ── 11. Outlier Detection (IQR + Boxplots) ──────────────────
def outlier_detection(df, name, num_cols=None, max_plots=6, color=None):
    """IQR-based outlier count + boxplots saved to disk."""
    if num_cols is None:
        num_cols = df.select_dtypes(include=np.number).columns.tolist()
    num_cols = [c for c in num_cols if c in df.columns]
    if not num_cols:
        print('  No numeric columns for outlier detection.')
        return {}

    print(f"\n{'='*60}")
    print(f"  OUTLIER DETECTION (IQR) — {name}")
    print(f"{'='*60}")

    outlier_info = {}
    for col in num_cols:
        Q1  = df[col].quantile(0.25)
        Q3  = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lo  = Q1 - 1.5 * IQR
        hi  = Q3 + 1.5 * IQR
        n_out = int(((df[col] < lo) | (df[col] > hi)).sum())
        outlier_info[col] = {'Q1': Q1, 'Q3': Q3, 'IQR': IQR,
                             'lower_bound': lo, 'upper_bound': hi,
                             'outlier_count': n_out}
        print(f"  {col:<28} Q1={Q1:.2f}  Q3={Q3:.2f}  IQR={IQR:.2f}  "
              f"Bounds=[{lo:.2f}, {hi:.2f}]  Outliers={n_out}")

    # Boxplots
    plot_cols = num_cols[:max_plots]
    ncols = min(3, len(plot_cols))
    nrows = int(np.ceil(len(plot_cols) / ncols))
    fig, axes = plt.subplots(nrows, ncols,
                             figsize=(5 * ncols, 4 * nrows))
    axes = np.array(axes).flatten()
    clr  = color or PALETTE[0]
    for i, col in enumerate(plot_cols):
        axes[i].boxplot(df[col].dropna(), patch_artist=True,
                        boxprops=dict(facecolor=clr, alpha=0.7))
        axes[i].set_title(col, fontsize=9)
        axes[i].set_xlabel('')
    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])
    fig.suptitle(f'Boxplots — {name}', fontsize=12, y=1.01)
    plt.tight_layout()
    path = PLOTS_DIR / f"{name.replace(' ', '_')}_boxplots.png"
    plt.savefig(path, dpi=120, bbox_inches='tight')
    plt.close()
    print(f"  Boxplot saved → {path}")
    return outlier_info


# ── 12. Frequency Distribution ──────────────────────────────
def frequency_distribution(df, name, max_cats=10, color=None):
    """Value counts for categorical columns + bar chart."""
    cat_cols = df.select_dtypes(include='object').columns.tolist()
    if not cat_cols:
        print('  No categorical columns found.')
        return {}
    print(f"\n{'='*60}")
    print(f"  FREQUENCY DISTRIBUTION — {name}")
    print(f"{'='*60}")
    freq_results = {}
    clr = color or PALETTE[1]
    for col in cat_cols:
        vc = df[col].value_counts().head(max_cats)
        freq_results[col] = vc.to_dict()
        print(f"\n  [{col}]")
        print(vc.to_string())

    # Bar chart for first categorical with ≤20 unique vals
    chart_cols = [c for c in cat_cols if df[c].nunique() <= 20]
    if chart_cols:
        col  = chart_cols[0]
        vc   = df[col].value_counts().head(15)
        fig, ax = plt.subplots(figsize=(8, 4))
        vc.plot(kind='bar', ax=ax, color=clr, alpha=0.85, edgecolor='white')
        ax.set_title(f'Frequency — {col} ({name})', fontsize=11)
        ax.set_xlabel(col)
        ax.set_ylabel('Count')
        plt.xticks(rotation=45, ha='right', fontsize=8)
        plt.tight_layout()
        path = PLOTS_DIR / f"{name.replace(' ', '_')}_freq_{col}.png"
        plt.savefig(path, dpi=120, bbox_inches='tight')
        plt.close()
        print(f"  Bar chart saved → {path}")
    return freq_results


# ── 13. Correlation Analysis ─────────────────────────────────
def correlation_analysis(df, name, color='Blues'):
    """Pearson correlation matrix + heatmap for numeric columns."""
    num_df = df.select_dtypes(include=np.number)
    if num_df.shape[1] < 2:
        print(f"  Not enough numeric columns for correlation in {name}.")
        return None
    corr = num_df.corr()
    print(f"\n{'='*60}")
    print(f"  CORRELATION MATRIX — {name}")
    print(f"{'='*60}")
    print(corr.round(3).to_string())
    # Heatmap
    fig, ax = plt.subplots(figsize=(max(6, num_df.shape[1]),
                                    max(5, num_df.shape[1] - 1)))
    sns.heatmap(corr, annot=True, fmt='.2f', cmap=color,
                linewidths=0.5, ax=ax, cbar_kws={'shrink': 0.8})
    ax.set_title(f'Correlation Heatmap — {name}', fontsize=11)
    plt.tight_layout()
    path = PLOTS_DIR / f"{name.replace(' ', '_')}_correlation.png"
    plt.savefig(path, dpi=120, bbox_inches='tight')
    plt.close()
    print(f"  Heatmap saved → {path}")
    return corr


# ── 14. Memory Usage per Column ──────────────────────────────
def memory_usage(df, name):
    """Detailed memory usage per column."""
    mem = df.memory_usage(deep=True)
    mem_df = pd.DataFrame({
        'Column':   ['Index'] + list(df.columns),
        'Bytes':    mem.values,
        'KB':       (mem.values / 1024).round(3)
    }).sort_values('Bytes', ascending=False)
    total_kb = mem.sum() / 1024
    print(f"\n{'='*60}")
    print(f"  MEMORY USAGE — {name}")
    print(f"{'='*60}")
    print(mem_df.to_string(index=False))
    print(f"\n  TOTAL : {total_kb:.2f} KB  ({total_kb/1024:.4f} MB)")
    return mem_df


# ── Master runner: applies all 14 checks ─────────────────────
def run_full_profile(df, name, id_col=None,
                     force_numeric_cols=None,
                     blank_extra_cols=None,
                     dataset_color=None,
                     corr_cmap='Blues'):
    """
    Run all 14 profiling checks on df.
    Parameters
    ----------
    df                : pd.DataFrame
    name              : str  — display name for this dataset
    id_col            : str  — optional unique-ID column for duplicate check
    force_numeric_cols: list — override auto-detect for outlier/corr
    blank_extra_cols  : list — extra non-object cols to check for blanks
    dataset_color     : str  — hex color for charts
    corr_cmap         : str  — seaborn colormap for correlation heatmap
    """
    print('\n' + '█'*70)
    print(f'  PROFILING START : {name}')
    print('█'*70)

    result = {'name': name}

    result['overview']        = overview(df, name)
    result['columns']         = column_names(df, name)
    result['dtypes']          = data_types(df, name)
    result['stats']           = summary_statistics(df, name)
    result['duplicates']      = duplicate_analysis(df, name, id_col=id_col)
    result['missing']         = missing_values(df, name)
    result['blanks']          = blank_whitespace(df, name, extra_cols=blank_extra_cols)
    result['unique']          = unique_values(df, name)
    result['cardinality']     = cardinality(df, name)
    result['numeric_cols']    = numeric_columns(df, name)
    num_cols_for_analysis     = force_numeric_cols or result['numeric_cols']
    result['outliers']        = outlier_detection(df, name,
                                                  num_cols=num_cols_for_analysis,
                                                  color=dataset_color)
    result['frequency']       = frequency_distribution(df, name,
                                                       color=dataset_color)
    result['correlation']     = correlation_analysis(df, name, color=corr_cmap)
    result['memory']          = memory_usage(df, name)

    MASTER_RESULTS[name] = result
    print(f"\n  ✓ Profiling complete for [{name}]")
    print('█'*70 + '\n')
    return result


print('Profiling engine ready.')

Profiling engine ready.

## Phase 3 — Dataset 1: Pakistan Cities (pk.csv)

In [22]:
pk_df = pd.read_csv(r"D:\telecom-customer-analytics-platform\data\raw\pk.csv")

print("pk.csv loaded. Shape:", pk_df.shape)
pk_df.head()

pk.csv loaded. Shape: (146, 9)

           city     lat     lng   country iso2 admin_name capital    population  population_proper
0       Karachi 24.8600 67.0100  Pakistan   PK      Sindh   admin 14835000.0000      14835000.0000
1        Lahore 31.5497 74.3436  Pakistan   PK     Punjab   admin 11021000.0000      11021000.0000
2  Sialkot City 32.5000 74.5333  Pakistan   PK     Punjab   minor  3893672.0000       3893672.0000
3    Faisalabad 31.4180 73.0790  Pakistan   PK     Punjab   minor  3203846.0000       3203846.0000
4    Rawalpindi 33.6007 73.0679  Pakistan   PK     Punjab   minor  2098231.0000       2098231.0000

In [23]:
# ── Dataset-Specific Notes ────────────────────────────────────
# • Geographic reference data (146 Pakistani cities)
# • No customer ID column
# • 'capital' column has low cardinality (admin / minor / primary / NaN)
# • population & population_proper should be equal or near-equal
# • lat/lng are continuous geographic coordinates — outlier detection meaningful

pk_result = run_full_profile(
    df                = pk_df,
    name              = 'PK_Cities',
    id_col            = 'city',           # city acts as the identifier
    force_numeric_cols= ['lat', 'lng', 'population', 'population_proper'],
    blank_extra_cols  = ['admin_name', 'capital'],
    dataset_color     = PALETTE[0],        # blue
    corr_cmap         = 'YlOrRd'
)

██████████████████████████████████████████████████████████████████████
  PROFILING START : PK_Cities
██████████████████████████████████████████████████████████████████████

============================================================
  DATASET OVERVIEW — PK_Cities
============================================================
  Rows               : 146
  Columns            : 9
  Memory Usage (MB)  : 0.0489

============================================================
  COLUMN NAMES — PK_Cities
============================================================
    1. city
    2. lat
    3. lng
    4. country
    5. iso2
    6. admin_name
    7. capital
    8. population
    9. population_proper

============================================================
  DATA TYPES — PK_Cities
============================================================
           Column   DType
             city  object
              lat float64
              lng float64
          country  object
             iso2  object
       admin_name  object
          capital  object
       population float64
population_proper float64

============================================================
  SUMMARY STATISTICS — PK_Cities
============================================================

[Numeric]
           lat      lng    population  population_proper
count 146.0000 146.0000       88.0000            88.0000
mean   30.9300  71.0196   646726.5114        645972.4659
std     2.9526   2.7251  2016112.5185       2016335.9294
min    24.6558  62.3225     8851.0000          8851.0000
25%    28.9230  68.8456    72421.0000         70183.7500
50%    30.9941  71.7599   128003.5000        128003.5000
75%    33.4200  73.1840   303972.2500        303972.2500
max    36.3078  75.1583 14835000.0000      14835000.0000

[Categorical]
           city   country iso2 admin_name capital
count       146       146  146        146     114
unique      145         1    1          7       3
top     Khuzdar  Pakistan   PK     Punjab   minor
freq          2       146  146         57     109

============================================================
  DUPLICATE ANALYSIS — PK_Cities
============================================================
  Duplicate Rows       : 0
  Duplicate Percentage : 0.00%
  Duplicate 'city'     : 1

============================================================
  MISSING VALUES — PK_Cities
============================================================
                   Missing_Count  Missing_Pct
population                    58      39.7300
population_proper             58      39.7300
capital                       32      21.9200

  Total Missing Cells  : 148
  Total Cells          : 1314

============================================================
  BLANK / WHITESPACE VALUES — PK_Cities
============================================================
  No blank/whitespace values found.

============================================================
  UNIQUE VALUES — PK_Cities
============================================================
           Column  Unique_Count  Total_Count  Unique_Pct
             city           145          146     99.3200
              lat           146          146    100.0000
              lng           145          146     99.3200
          country             1          146      0.6800
             iso2             1          146      0.6800
       admin_name             7          146      4.7900
          capital             3          146      2.0500
       population            87          146     59.5900
population_proper            87          146     59.5900

============================================================
  CARDINALITY — PK_Cities
============================================================
           Column  Unique Cardinality
             city     145        High
              lat     146        High
              lng     145        High
          country       1         Low
             iso2       1         Low
       admin_name       7      Medium
          capital       3         Low
       population      87        High
population_proper      87        High

============================================================
  NUMERIC COLUMNS — PK_Cities
============================================================
  lat                            float64
  lng                            float64
  population                     float64
  population_proper              float64

  Total Numeric Columns : 4

============================================================
  OUTLIER DETECTION (IQR) — PK_Cities
============================================================
  lat                          Q1=28.92  Q3=33.42  IQR=4.50  Bounds=[22.18, 40.17]  Outliers=0
  lng                          Q1=68.85  Q3=73.18  IQR=4.34  Bounds=[62.34, 79.69]  Outliers=1
  population                   Q1=72421.00  Q3=303972.25  IQR=231551.25  Bounds=[-274905.88, 651299.12]  Outliers=12
  population_proper            Q1=70183.75  Q3=303972.25  IQR=233788.50  Bounds=[-280499.00, 654655.00]  Outliers=12
  Boxplot saved → profiling_outputs\plots\PK_Cities_boxplots.png

============================================================
  FREQUENCY DISTRIBUTION — PK_Cities
============================================================

  [city]
city
Khuzdar        2
Karachi        1
Attock City    1
Haripur        1
Shikarpur      1
Rawala Kot     1
Hafizabad      1
Lodhran        1
Malakand       1
Batgram        1

  [country]
country
Pakistan    146

  [iso2]
iso2
PK    146

  [admin_name]
admin_name
Punjab                57
Khyber Pakhtunkhwa    28
Balochistān           26
Sindh                 22
Azad Kashmir           6
Gilgit-Baltistan       6
Islāmābād              1

  [capital]
capital
minor      109
admin        4
primary      1
  Bar chart saved → profiling_outputs\plots\PK_Cities_freq_country.png

============================================================
  CORRELATION MATRIX — PK_Cities
============================================================
                      lat     lng  population  population_proper
lat                1.0000  0.7240     -0.1620            -0.1620
lng                0.7240  1.0000     -0.0530            -0.0520
population        -0.1620 -0.0530      1.0000             1.0000
population_proper -0.1620 -0.0520      1.0000             1.0000
  Heatmap saved → profiling_outputs\plots\PK_Cities_correlation.png

============================================================
  MEMORY USAGE — PK_Cities
============================================================
           Column  Bytes      KB
       admin_name  11062 10.8030
             city   9614  9.3890
          country   9490  9.2680
             iso2   8614  8.4120
          capital   8094  7.9040
              lat   1168  1.1410
              lng   1168  1.1410
       population   1168  1.1410
population_proper   1168  1.1410
            Index    132  0.1290

  TOTAL : 50.47 KB  (0.0493 MB)

  ✓ Profiling complete for [PK_Cities]
██████████████████████████████████████████████████████████████████████

In [24]:
# ── Dataset-Specific: Population Discrepancy Check ───────────
print('='*60)
print('  POPULATION vs POPULATION_PROPER CHECK — PK_Cities')
print('='*60)
mismatch = pk_df[pk_df['population'] != pk_df['population_proper']]
print(f'  Mismatches : {len(mismatch)}')
if len(mismatch) > 0:
    print(mismatch[['city', 'population', 'population_proper']].to_string(index=False))

# ── Capital Type Breakdown ────────────────────────────────────
print('\n  Capital Type Distribution:')
print(pk_df['capital'].value_counts(dropna=False))

============================================================
  POPULATION vs POPULATION_PROPER CHECK — PK_Cities
============================================================
  Mismatches : 60
               city  population  population_proper
               Zhob  88356.0000         50537.0000
             Gwadar  51901.0000         23364.0000
     Hyderabad City         NaN                NaN
            Narowal         NaN                NaN
     Khairpur Mir’s         NaN                NaN
           Khanewal         NaN                NaN
             Jhelum         NaN                NaN
            Haripur         NaN                NaN
          Shikarpur         NaN                NaN
         Rawala Kot         NaN                NaN
          Hafizabad         NaN                NaN
            Lodhran         NaN                NaN
           Malakand         NaN                NaN
        Attock City         NaN                NaN
            Batgram         NaN                NaN
            Matiari         NaN                NaN
             Ghotki         NaN                NaN
    Naushahro Firoz         NaN                NaN
            Alpurai         NaN                NaN
               Bagh         NaN                NaN
             Daggar         NaN                NaN
       Bahawalnagar         NaN                NaN
              Leiah         NaN                NaN
Tando Muhammad Khan         NaN                NaN
            Chakwal         NaN                NaN
            Khushab         NaN                NaN
              Badin         NaN                NaN
              Lakki         NaN                NaN
           Rajanpur         NaN                NaN
      Dera Allahyar         NaN                NaN
        Shahdad Kot         NaN                NaN
             Pishin         NaN                NaN
            Sanghar         NaN                NaN
          Upper Dir         NaN                NaN
             Thatta         NaN                NaN
  Dera Murad Jamali         NaN                NaN
              Kohlu         NaN                NaN
            Mastung         NaN                NaN
               Dasu         NaN                NaN
           Athmuqam         NaN                NaN
            Loralai         NaN                NaN
            Barkhan         NaN                NaN
    Musa Khel Bazar         NaN                NaN
             Ziarat         NaN                NaN
            Gandava         NaN                NaN
               Sibi         NaN                NaN
         Dera Bugti         NaN                NaN
             Eidgah         NaN                NaN
             Turbat         NaN                NaN
              Uthal         NaN                NaN
            Khuzdar         NaN                NaN
             Chilas         NaN                NaN
              Kalat         NaN                NaN
            Panjgur         NaN                NaN
             Gakuch         NaN                NaN
     Qila Saifullah         NaN                NaN
             Kharan         NaN                NaN
            Aliabad         NaN                NaN
             Awaran         NaN                NaN
          Dalbandin         NaN                NaN

  Capital Type Distribution:
capital
minor      109
NaN         32
admin        4
primary      1
Name: count, dtype: int64

## Phase 4 — Dataset 2: IBM Telco Churn Original (WA_Fn CSV)

In [25]:
# ── Load ─────────────────────────────────────────────────────
telco_csv_df = pd.read_csv(r"D:\telecom-customer-analytics-platform\data\raw\WA_Fn-UseC_-Telco-Customer-Churn.csv")

# Phase 3 — Dataset 1: Pakistan Cities (pk.csv)
pk_df = pd.read_csv(r"D:\telecom-customer-analytics-platform\data\raw\pk.csv")

print("pk.csv loaded. Shape:", pk_df.shape)
pk_df.head()
print('WA_Fn CSV loaded. Shape:', telco_csv_df.shape)
telco_csv_df.head()

pk.csv loaded. Shape: (146, 9)
WA_Fn CSV loaded. Shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.8500,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.9500,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.8500,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.3000,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.7000,151.65,Yes

In [26]:
# ── Dataset-Specific Notes ────────────────────────────────────
# • Classic IBM Telco dataset (7043 rows, 21 columns)
# • TotalCharges is numeric but may contain blank strings → converted
# • SeniorCitizen is 0/1 integer (binary flag, not really numeric)
# • customerID is high-cardinality identifier

# Pre-processing: fix TotalCharges before profiling
telco_csv_df['TotalCharges'] = pd.to_numeric(
    telco_csv_df['TotalCharges'].astype(str).str.strip(),
    errors='coerce'
)
blank_tc = telco_csv_df['TotalCharges'].isna().sum()
print(f'TotalCharges blanks coerced to NaN : {blank_tc}')

telco_csv_result = run_full_profile(
    df                 = telco_csv_df,
    name               = 'Telco_CSV',
    id_col             = 'customerID',
    force_numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges'],
    blank_extra_cols   = ['TotalCharges'],
    dataset_color      = PALETTE[2],    # green
    corr_cmap          = 'Greens'
)

TotalCharges blanks coerced to NaN : 11

██████████████████████████████████████████████████████████████████████
  PROFILING START : Telco_CSV
██████████████████████████████████████████████████████████████████████

============================================================
  DATASET OVERVIEW — Telco_CSV
============================================================
  Rows               : 7,043
  Columns            : 21
  Memory Usage (MB)  : 7.4196

============================================================
  COLUMN NAMES — Telco_CSV
============================================================
    1. customerID
    2. gender
    3. SeniorCitizen
    4. Partner
    5. Dependents
    6. tenure
    7. PhoneService
    8. MultipleLines
    9. InternetService
   10. OnlineSecurity
   11. OnlineBackup
   12. DeviceProtection
   13. TechSupport
   14. StreamingTV
   15. StreamingMovies
   16. Contract
   17. PaperlessBilling
   18. PaymentMethod
   19. MonthlyCharges
   20. TotalCharges
   21. Churn

============================================================
  DATA TYPES — Telco_CSV
============================================================
          Column   DType
      customerID  object
          gender  object
   SeniorCitizen   int64
         Partner  object
      Dependents  object
          tenure   int64
    PhoneService  object
   MultipleLines  object
 InternetService  object
  OnlineSecurity  object
    OnlineBackup  object
DeviceProtection  object
     TechSupport  object
     StreamingTV  object
 StreamingMovies  object
        Contract  object
PaperlessBilling  object
   PaymentMethod  object
  MonthlyCharges float64
    TotalCharges float64
           Churn  object

============================================================
  SUMMARY STATISTICS — Telco_CSV
============================================================

[Numeric]
       SeniorCitizen    tenure  MonthlyCharges  TotalCharges
count      7043.0000 7043.0000       7043.0000     7032.0000
mean          0.1621   32.3711         64.7617     2283.3004
std           0.3686   24.5595         30.0900     2266.7714
min           0.0000    0.0000         18.2500       18.8000
25%           0.0000    9.0000         35.5000      401.4500
50%           0.0000   29.0000         70.3500     1397.4750
75%           0.0000   55.0000         89.8500     3794.7375
max           1.0000   72.0000        118.7500     8684.8000

[Categorical]
        customerID gender Partner Dependents PhoneService MultipleLines InternetService OnlineSecurity OnlineBackup  \
count         7043   7043    7043       7043         7043          7043            7043           7043         7043
unique        7043      2       2          2            2             3               3              3            3
top     7590-VHVEG   Male      No         No          Yes            No     Fiber optic             No           No
freq             1   3555    3641       4933         6361          3390            3096           3498         3088

       DeviceProtection TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling     PaymentMethod  \
count              7043        7043        7043            7043            7043             7043              7043
unique                3           3           3               3               3                2                 4
top                  No          No          No              No  Month-to-month              Yes  Electronic check
freq               3095        3473        2810            2785            3875             4171              2365

       Churn
count   7043
unique     2
top       No
freq    5174

============================================================
  DUPLICATE ANALYSIS — Telco_CSV
============================================================
  Duplicate Rows       : 0
  Duplicate Percentage : 0.00%
  Duplicate 'customerID'     : 0

============================================================
  MISSING VALUES — Telco_CSV
============================================================
              Missing_Count  Missing_Pct
TotalCharges             11       0.1600

  Total Missing Cells  : 11
  Total Cells          : 147903

============================================================
  BLANK / WHITESPACE VALUES — Telco_CSV
============================================================
  No blank/whitespace values found.

============================================================
  UNIQUE VALUES — Telco_CSV
============================================================
          Column  Unique_Count  Total_Count  Unique_Pct
      customerID          7043         7043    100.0000
          gender             2         7043      0.0300
   SeniorCitizen             2         7043      0.0300
         Partner             2         7043      0.0300
      Dependents             2         7043      0.0300
          tenure            73         7043      1.0400
    PhoneService             2         7043      0.0300
   MultipleLines             3         7043      0.0400
 InternetService             3         7043      0.0400
  OnlineSecurity             3         7043      0.0400
    OnlineBackup             3         7043      0.0400
DeviceProtection             3         7043      0.0400
     TechSupport             3         7043      0.0400
     StreamingTV             3         7043      0.0400
 StreamingMovies             3         7043      0.0400
        Contract             3         7043      0.0400
PaperlessBilling             2         7043      0.0300
   PaymentMethod             4         7043      0.0600
  MonthlyCharges          1585         7043     22.5000
    TotalCharges          6530         7043     92.7200
           Churn             2         7043      0.0300

============================================================
  CARDINALITY — Telco_CSV
============================================================
          Column  Unique Cardinality
      customerID    7043        High
          gender       2         Low
   SeniorCitizen       2         Low
         Partner       2         Low
      Dependents       2         Low
          tenure      73        High
    PhoneService       2         Low
   MultipleLines       3         Low
 InternetService       3         Low
  OnlineSecurity       3         Low
    OnlineBackup       3         Low
DeviceProtection       3         Low
     TechSupport       3         Low
     StreamingTV       3         Low
 StreamingMovies       3         Low
        Contract       3         Low
PaperlessBilling       2         Low
   PaymentMethod       4         Low
  MonthlyCharges    1585        High
    TotalCharges    6530        High
           Churn       2         Low

============================================================
  NUMERIC COLUMNS — Telco_CSV
============================================================
  SeniorCitizen                  int64
  tenure                         int64
  MonthlyCharges                 float64
  TotalCharges                   float64

  Total Numeric Columns : 4

============================================================
  OUTLIER DETECTION (IQR) — Telco_CSV
============================================================
  tenure                       Q1=9.00  Q3=55.00  IQR=46.00  Bounds=[-60.00, 124.00]  Outliers=0
  MonthlyCharges               Q1=35.50  Q3=89.85  IQR=54.35  Bounds=[-46.02, 171.38]  Outliers=0
  TotalCharges                 Q1=401.45  Q3=3794.74  IQR=3393.29  Bounds=[-4688.48, 8884.67]  Outliers=0
  Boxplot saved → profiling_outputs\plots\Telco_CSV_boxplots.png

============================================================
  FREQUENCY DISTRIBUTION — Telco_CSV
============================================================

  [customerID]
customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
5855-EIBDE    1
8166-ZZTFS    1
0129-KPTWJ    1
9128-CPXKI    1
9509-MPYOD    1

  [gender]
gender
Male      3555
Female    3488

  [Partner]
Partner
No     3641
Yes    3402

  [Dependents]
Dependents
No     4933
Yes    2110

  [PhoneService]
PhoneService
Yes    6361
No      682

  [MultipleLines]
MultipleLines
No                  3390
Yes                 2971
No phone service     682

  [InternetService]
InternetService
Fiber optic    3096
DSL            2421
No             1526

  [OnlineSecurity]
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526

  [OnlineBackup]
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526

  [DeviceProtection]
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526

  [TechSupport]
TechSupport
No                     3473
Yes                    2044
No internet service    1526

  [StreamingTV]
StreamingTV
No                     2810
Yes                    2707
No internet service    1526

  [StreamingMovies]
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526

  [Contract]
Contract
Month-to-month    3875
Two year          1695
One year          1473

  [PaperlessBilling]
PaperlessBilling
Yes    4171
No     2872

  [PaymentMethod]
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522

  [Churn]
Churn
No     5174
Yes    1869
  Bar chart saved → profiling_outputs\plots\Telco_CSV_freq_gender.png

============================================================
  CORRELATION MATRIX — Telco_CSV
============================================================
                SeniorCitizen  tenure  MonthlyCharges  TotalCharges
SeniorCitizen          1.0000  0.0170          0.2200        0.1020
tenure                 0.0170  1.0000          0.2480        0.8260
MonthlyCharges         0.2200  0.2480          1.0000        0.6510
TotalCharges           0.1020  0.8260          0.6510        1.0000
  Heatmap saved → profiling_outputs\plots\Telco_CSV_correlation.png

============================================================
  MEMORY USAGE — Telco_CSV
============================================================
          Column  Bytes       KB
   PaymentMethod 532241 519.7670
        Contract 481045 469.7710
      customerID 471881 460.8210
 InternetService 445822 435.3730
 StreamingMovies 444211 433.8000
     StreamingTV 444186 433.7750
    OnlineBackup 443908 433.5040
DeviceProtection 443901 433.4970
     TechSupport 443523 433.1280
  OnlineSecurity 443498 433.1040
          gender 436599 426.3660
   MultipleLines 428056 418.0230
    PhoneService 421898 412.0100
PaperlessBilling 419708 409.8710
         Partner 418939 409.1200
      Dependents 417647 407.8580
           Churn 417406 407.6230
          tenure  56344  55.0230
   SeniorCitizen  56344  55.0230
  MonthlyCharges  56344  55.0230
    TotalCharges  56344  55.0230
           Index    132   0.1290

  TOTAL : 7597.63 KB  (7.4196 MB)

  ✓ Profiling complete for [Telco_CSV]
██████████████████████████████████████████████████████████████████████

In [27]:
# ── Dataset-Specific: Churn Rate Breakdown ───────────────────
print('='*60)
print('  CHURN RATE BREAKDOWN — Telco_CSV')
print('='*60)
churn_vc = telco_csv_df['Churn'].value_counts()
churn_pct = (churn_vc / len(telco_csv_df) * 100).round(2)
churn_summary = pd.DataFrame({'Count': churn_vc, 'Percentage': churn_pct})
print(churn_summary)

# ── SeniorCitizen Flag Breakdown ─────────────────────────────
print('\n  SeniorCitizen Distribution (0=No, 1=Yes):')
print(telco_csv_df['SeniorCitizen'].value_counts())

# ── Charges by Contract Type ─────────────────────────────────
print('\n  Monthly Charges by Contract Type:')
print(telco_csv_df.groupby('Contract')['MonthlyCharges']
      .agg(['mean', 'median', 'min', 'max']).round(2))

============================================================
  CHURN RATE BREAKDOWN — Telco_CSV
============================================================
       Count  Percentage
Churn
No      5174     73.4600
Yes     1869     26.5400

  SeniorCitizen Distribution (0=No, 1=Yes):
SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

  Monthly Charges by Contract Type:
                  mean  median     min      max
Contract
Month-to-month 66.4000 73.2500 18.7500 117.4500
One year       65.0500 68.7500 18.2500 118.6000
Two year       60.7700 64.3500 18.4000 118.7500

## Phase 5 — Dataset 3: Telco Churn Extended (Excel)

In [28]:
# ── Load ─────────────────────────────────────────────────────
telco_xl_df = pd.read_excel(r'D:\telecom-customer-analytics-platform\data\raw\Telco_customer_churn.xlsx',
                            sheet_name='Telco_Churn')
print('Excel loaded. Shape:', telco_xl_df.shape)
telco_xl_df.head()

Excel loaded. Shape: (7043, 33)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.9641,-118.2728,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.8500,108.1500,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.0593,-118.3074,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.7000,151.6500,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.0480,-118.2940,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.6500,820.5000,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.0621,-118.3157,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.8000,3046.0500,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.0392,-118.2663,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.7000,5036.3000,Yes,1,89,5340,Competitor had better devices

In [30]:
telco_xl_df[telco_xl_num_cols].dtypes

Latitude           float64
Longitude          float64
Tenure Months        int64
Monthly Charges    float64
Total Charges       object
Churn Value          int64
Churn Score          int64
CLTV                 int64
dtype: object

In [31]:
print("Blank Total Charges:")
print(
    telco_xl_df["Total Charges"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

Blank Total Charges:
11

In [32]:
telco_xl_df["Total Charges"] = (
    pd.to_numeric(
        telco_xl_df["Total Charges"],
        errors="coerce"
    )
)

In [33]:
print(telco_xl_df["Total Charges"].dtype)

float64

In [34]:
# ── Dataset-Specific Notes ────────────────────────────────────
# • Extended IBM Telco (7043 rows, 33 columns)
# • Adds: Churn Score, CLTV, Churn Reason, geographic columns
# • 'Lat Long' is a combined string — not usable as numeric directly
# • Some columns overlap with WA_Fn CSV (different naming convention)

# Drop 'Lat Long' combined string column before numeric analysis
# (Latitude and Longitude are already separate)
telco_xl_num_cols = [
    'Latitude', 'Longitude', 'Tenure Months',
    'Monthly Charges', 'Total Charges',
    'Churn Value', 'Churn Score', 'CLTV'
]

telco_xl_result = run_full_profile(
    df                 = telco_xl_df,
    name               = 'Telco_Excel',
    id_col             = 'CustomerID',
    force_numeric_cols = telco_xl_num_cols,
    dataset_color      = PALETTE[3],      # purple
    corr_cmap          = 'Purples'
)

██████████████████████████████████████████████████████████████████████
  PROFILING START : Telco_Excel
██████████████████████████████████████████████████████████████████████

============================================================
  DATASET OVERVIEW — Telco_Excel
============================================================
  Rows               : 7,043
  Columns            : 33
  Memory Usage (MB)  : 10.3374

============================================================
  COLUMN NAMES — Telco_Excel
============================================================
    1. CustomerID
    2. Count
    3. Country
    4. State
    5. City
    6. Zip Code
    7. Lat Long
    8. Latitude
    9. Longitude
   10. Gender
   11. Senior Citizen
   12. Partner
   13. Dependents
   14. Tenure Months
   15. Phone Service
   16. Multiple Lines
   17. Internet Service
   18. Online Security
   19. Online Backup
   20. Device Protection
   21. Tech Support
   22. Streaming TV
   23. Streaming Movies
   24. Contract
   25. Paperless Billing
   26. Payment Method
   27. Monthly Charges
   28. Total Charges
   29. Churn Label
   30. Churn Value
   31. Churn Score
   32. CLTV
   33. Churn Reason

============================================================
  DATA TYPES — Telco_Excel
============================================================
           Column   DType
       CustomerID  object
            Count   int64
          Country  object
            State  object
             City  object
         Zip Code   int64
         Lat Long  object
         Latitude float64
        Longitude float64
           Gender  object
   Senior Citizen  object
          Partner  object
       Dependents  object
    Tenure Months   int64
    Phone Service  object
   Multiple Lines  object
 Internet Service  object
  Online Security  object
    Online Backup  object
Device Protection  object
     Tech Support  object
     Streaming TV  object
 Streaming Movies  object
         Contract  object
Paperless Billing  object
   Payment Method  object
  Monthly Charges float64
    Total Charges float64
      Churn Label  object
      Churn Value   int64
      Churn Score   int64
             CLTV   int64
     Churn Reason  object

============================================================
  SUMMARY STATISTICS — Telco_Excel
============================================================

[Numeric]
          Count   Zip Code  Latitude  Longitude  Tenure Months  Monthly Charges  Total Charges  Churn Value  \
count 7043.0000  7043.0000 7043.0000  7043.0000      7043.0000        7043.0000      7032.0000    7043.0000
mean     1.0000 93521.9646   36.2824  -119.7989        32.3711          64.7617      2283.3004       0.2654
std      0.0000  1865.7946    2.4557     2.1579        24.5595          30.0900      2266.7714       0.4416
min      1.0000 90001.0000   32.5558  -124.3014         0.0000          18.2500        18.8000       0.0000
25%      1.0000 92102.0000   34.0309  -121.8154         9.0000          35.5000       401.4500       0.0000
50%      1.0000 93552.0000   36.3918  -119.7309        29.0000          70.3500      1397.4750       0.0000
75%      1.0000 95351.0000   38.2249  -118.0432        55.0000          89.8500      3794.7375       1.0000
max      1.0000 96161.0000   41.9621  -114.1929        72.0000         118.7500      8684.8000       1.0000

       Churn Score      CLTV
count    7043.0000 7043.0000
mean       58.6994 4400.2958
std        21.5251 1183.0572
min         5.0000 2003.0000
25%        40.0000 3469.0000
50%        61.0000 4527.0000
75%        75.0000 5380.5000
max       100.0000 6500.0000

[Categorical]
        CustomerID        Country       State         City                Lat Long Gender Senior Citizen Partner  \
count         7043           7043        7043         7043                    7043   7043           7043    7043
unique        7043              1           1         1129                    1652      2              2       2
top     3668-QPYBK  United States  California  Los Angeles  33.964131, -118.272783   Male             No      No
freq             1           7043        7043          305                       5   3555           5901    3641

       Dependents Phone Service Multiple Lines Internet Service Online Security Online Backup Device Protection  \
count        7043          7043           7043             7043            7043          7043              7043
unique          2             2              3                3               3             3                 3
top            No           Yes             No      Fiber optic              No            No                No
freq         5416          6361           3390             3096            3498          3088              3095

       Tech Support Streaming TV Streaming Movies        Contract Paperless Billing    Payment Method Churn Label  \
count          7043         7043             7043            7043              7043              7043        7043
unique            3            3                3               3                 2                 4           2
top              No           No               No  Month-to-month               Yes  Electronic check          No
freq           3473         2810             2785            3875              4171              2365        5174

                      Churn Reason
count                         1869
unique                          20
top     Attitude of support person
freq                           192

============================================================
  DUPLICATE ANALYSIS — Telco_Excel
============================================================
  Duplicate Rows       : 0
  Duplicate Percentage : 0.00%
  Duplicate 'CustomerID'     : 0

============================================================
  MISSING VALUES — Telco_Excel
============================================================
               Missing_Count  Missing_Pct
Churn Reason            5174      73.4600
Total Charges             11       0.1600

  Total Missing Cells  : 5185
  Total Cells          : 232419

============================================================
  BLANK / WHITESPACE VALUES — Telco_Excel
============================================================
  No blank/whitespace values found.

============================================================
  UNIQUE VALUES — Telco_Excel
============================================================
           Column  Unique_Count  Total_Count  Unique_Pct
       CustomerID          7043         7043    100.0000
            Count             1         7043      0.0100
          Country             1         7043      0.0100
            State             1         7043      0.0100
             City          1129         7043     16.0300
         Zip Code          1652         7043     23.4600
         Lat Long          1652         7043     23.4600
         Latitude          1652         7043     23.4600
        Longitude          1651         7043     23.4400
           Gender             2         7043      0.0300
   Senior Citizen             2         7043      0.0300
          Partner             2         7043      0.0300
       Dependents             2         7043      0.0300
    Tenure Months            73         7043      1.0400
    Phone Service             2         7043      0.0300
   Multiple Lines             3         7043      0.0400
 Internet Service             3         7043      0.0400
  Online Security             3         7043      0.0400
    Online Backup             3         7043      0.0400
Device Protection             3         7043      0.0400
     Tech Support             3         7043      0.0400
     Streaming TV             3         7043      0.0400
 Streaming Movies             3         7043      0.0400
         Contract             3         7043      0.0400
Paperless Billing             2         7043      0.0300
   Payment Method             4         7043      0.0600
  Monthly Charges          1585         7043     22.5000
    Total Charges          6530         7043     92.7200
      Churn Label             2         7043      0.0300
      Churn Value             2         7043      0.0300
      Churn Score            85         7043      1.2100
             CLTV          3438         7043     48.8100
     Churn Reason            20         7043      0.2800

============================================================
  CARDINALITY — Telco_Excel
============================================================
           Column  Unique Cardinality
       CustomerID    7043        High
            Count       1         Low
          Country       1         Low
            State       1         Low
             City    1129        High
         Zip Code    1652        High
         Lat Long    1652        High
         Latitude    1652        High
        Longitude    1651        High
           Gender       2         Low
   Senior Citizen       2         Low
          Partner       2         Low
       Dependents       2         Low
    Tenure Months      73        High
    Phone Service       2         Low
   Multiple Lines       3         Low
 Internet Service       3         Low
  Online Security       3         Low
    Online Backup       3         Low
Device Protection       3         Low
     Tech Support       3         Low
     Streaming TV       3         Low
 Streaming Movies       3         Low
         Contract       3         Low
Paperless Billing       2         Low
   Payment Method       4         Low
  Monthly Charges    1585        High
    Total Charges    6530        High
      Churn Label       2         Low
      Churn Value       2         Low
      Churn Score      85        High
             CLTV    3438        High
     Churn Reason      20      Medium

============================================================
  NUMERIC COLUMNS — Telco_Excel
============================================================
  Count                          int64
  Zip Code                       int64
  Latitude                       float64
  Longitude                      float64
  Tenure Months                  int64
  Monthly Charges                float64
  Total Charges                  float64
  Churn Value                    int64
  Churn Score                    int64
  CLTV                           int64

  Total Numeric Columns : 10

============================================================
  OUTLIER DETECTION (IQR) — Telco_Excel
============================================================
  Latitude                     Q1=34.03  Q3=38.22  IQR=4.19  Bounds=[27.74, 44.52]  Outliers=0
  Longitude                    Q1=-121.82  Q3=-118.04  IQR=3.77  Bounds=[-127.47, -112.38]  Outliers=0
  Tenure Months                Q1=9.00  Q3=55.00  IQR=46.00  Bounds=[-60.00, 124.00]  Outliers=0
  Monthly Charges              Q1=35.50  Q3=89.85  IQR=54.35  Bounds=[-46.02, 171.38]  Outliers=0
  Total Charges                Q1=401.45  Q3=3794.74  IQR=3393.29  Bounds=[-4688.48, 8884.67]  Outliers=0
  Churn Value                  Q1=0.00  Q3=1.00  IQR=1.00  Bounds=[-1.50, 2.50]  Outliers=0
  Churn Score                  Q1=40.00  Q3=75.00  IQR=35.00  Bounds=[-12.50, 127.50]  Outliers=0
  CLTV                         Q1=3469.00  Q3=5380.50  IQR=1911.50  Bounds=[601.75, 8247.75]  Outliers=0
  Boxplot saved → profiling_outputs\plots\Telco_Excel_boxplots.png

============================================================
  FREQUENCY DISTRIBUTION — Telco_Excel
============================================================

  [CustomerID]
CustomerID
3668-QPYBK    1
9169-BSVIN    1
0206-OYVOC    1
6418-HNFED    1
8805-JNRAZ    1
8439-LTUGF    1
1767-TGTKO    1
1194-HVAIF    1
1080-BWSYE    1
8387-UGUSU    1

  [Country]
Country
United States    7043

  [State]
State
California    7043

  [City]
City
Los Angeles      305
San Diego        150
San Jose         112
Sacramento       108
San Francisco    104
Fresno            64
Long Beach        60
Oakland           52
Stockton          44
Bakersfield       40

  [Lat Long]
Lat Long
33.964131, -118.272783    5
34.152875, -118.486056    5
32.912664, -116.635387    5
32.64164, -116.985026     5
32.607964, -117.059459    5
34.105493, -117.660934    5
34.141146, -117.655583    5
34.101608, -118.055848    5
33.992416, -117.807874    5
34.231318, -117.662032    5

  [Gender]
Gender
Male      3555
Female    3488

  [Senior Citizen]
Senior Citizen
No     5901
Yes    1142

  [Partner]
Partner
No     3641
Yes    3402

  [Dependents]
Dependents
No     5416
Yes    1627

  [Phone Service]
Phone Service
Yes    6361
No      682

  [Multiple Lines]
Multiple Lines
No                  3390
Yes                 2971
No phone service     682

  [Internet Service]
Internet Service
Fiber optic    3096
DSL            2421
No             1526

  [Online Security]
Online Security
No                     3498
Yes                    2019
No internet service    1526

  [Online Backup]
Online Backup
No                     3088
Yes                    2429
No internet service    1526

  [Device Protection]
Device Protection
No                     3095
Yes                    2422
No internet service    1526

  [Tech Support]
Tech Support
No                     3473
Yes                    2044
No internet service    1526

  [Streaming TV]
Streaming TV
No                     2810
Yes                    2707
No internet service    1526

  [Streaming Movies]
Streaming Movies
No                     2785
Yes                    2732
No internet service    1526

  [Contract]
Contract
Month-to-month    3875
Two year          1695
One year          1473

  [Paperless Billing]
Paperless Billing
Yes    4171
No     2872

  [Payment Method]
Payment Method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522

  [Churn Label]
Churn Label
No     5174
Yes    1869

  [Churn Reason]
Churn Reason
Attitude of support person                   192
Competitor offered higher download speeds    189
Competitor offered more data                 162
Don't know                                   154
Competitor made better offer                 140
Attitude of service provider                 135
Competitor had better devices                130
Network reliability                          103
Product dissatisfaction                      102
Price too high                                98
  Bar chart saved → profiling_outputs\plots\Telco_Excel_freq_Country.png

============================================================
  CORRELATION MATRIX — Telco_Excel
============================================================
                 Count  Zip Code  Latitude  Longitude  Tenure Months  Monthly Charges  Total Charges  Churn Value  Churn Score    CLTV
Count              NaN       NaN       NaN        NaN            NaN              NaN            NaN          NaN          NaN     NaN
Zip Code           NaN    1.0000    0.8960    -0.7840         0.0010          -0.0050        -0.0010       0.0030      -0.0030 -0.0040
Latitude           NaN    0.8960    1.0000    -0.8770        -0.0020          -0.0200        -0.0100      -0.0030      -0.0080  0.0010
Longitude          NaN   -0.7840   -0.8770     1.0000        -0.0020           0.0240         0.0090       0.0050       0.0040  0.0000
Tenure Months      NaN    0.0010   -0.0020    -0.0020         1.0000           0.2480         0.8260      -0.3520      -0.2250  0.3960
Monthly Charges    NaN   -0.0050   -0.0200     0.0240         0.2480           1.0000         0.6510       0.1930       0.1340  0.0990
Total Charges      NaN   -0.0010   -0.0100     0.0090         0.8260           0.6510         1.0000      -0.1990      -0.1240  0.3420
Churn Value        NaN    0.0030   -0.0030     0.0050        -0.3520           0.1930        -0.1990       1.0000       0.6650 -0.1270
Churn Score        NaN   -0.0030   -0.0080     0.0040        -0.2250           0.1340        -0.1240       0.6650       1.0000 -0.0800
CLTV               NaN   -0.0040    0.0010     0.0000         0.3960           0.0990         0.3420      -0.1270      -0.0800  1.0000
  Heatmap saved → profiling_outputs\plots\Telco_Excel_correlation.png

============================================================
  MEMORY USAGE — Telco_Excel
============================================================
           Column  Bytes       KB
         Lat Long 554827 541.8230
   Payment Method 532241 519.7670
          Country 493010 481.4550
         Contract 481045 469.7710
            State 471881 460.8210
       CustomerID 471881 460.8210
             City 466410 455.4790
 Internet Service 445822 435.3730
 Streaming Movies 444211 433.8000
     Streaming TV 444186 433.7750
    Online Backup 443908 433.5040
Device Protection 443901 433.4970
     Tech Support 443523 433.1280
  Online Security 443498 433.1040
           Gender 436599 426.3660
   Multiple Lines 428056 418.0230
    Phone Service 421898 412.0100
Paperless Billing 419708 409.8710
          Partner 418939 409.1200
      Churn Label 417406 407.6230
       Dependents 417164 407.3870
   Senior Citizen 416679 406.9130
     Churn Reason 319189 311.7080
    Tenure Months  56344  55.0230
        Longitude  56344  55.0230
         Latitude  56344  55.0230
         Zip Code  56344  55.0230
  Monthly Charges  56344  55.0230
    Total Charges  56344  55.0230
            Count  56344  55.0230
      Churn Value  56344  55.0230
      Churn Score  56344  55.0230
             CLTV  56344  55.0230
            Index    132   0.1290

  TOTAL : 10585.50 KB  (10.3374 MB)

  ✓ Profiling complete for [Telco_Excel]
██████████████████████████████████████████████████████████████████████

In [35]:
# ── Dataset-Specific: CLTV Segmentation ─────────────────────
print('='*60)
print('  CLTV DISTRIBUTION — Telco_Excel')
print('='*60)
telco_xl_df['CLTV_Segment'] = pd.qcut(
    telco_xl_df['CLTV'], q=4,
    labels=['Bronze', 'Silver', 'Gold', 'Platinum']
)
print(telco_xl_df['CLTV_Segment'].value_counts())

# ── Churn Reason Top 10 ──────────────────────────────────────
print('\n  Top 10 Churn Reasons:')
print(telco_xl_df['Churn Reason'].value_counts().head(10))

# ── Churn Score Stats ────────────────────────────────────────
print('\n  Churn Score Stats:')
print(telco_xl_df['Churn Score'].describe().round(2))

============================================================
  CLTV DISTRIBUTION — Telco_Excel
============================================================
CLTV_Segment
Bronze      1763
Platinum    1761
Gold        1760
Silver      1759
Name: count, dtype: int64

  Top 10 Churn Reasons:
Churn Reason
Attitude of support person                   192
Competitor offered higher download speeds    189
Competitor offered more data                 162
Don't know                                   154
Competitor made better offer                 140
Attitude of service provider                 135
Competitor had better devices                130
Network reliability                          103
Product dissatisfaction                      102
Price too high                                98
Name: count, dtype: int64

  Churn Score Stats:
count   7043.0000
mean      58.7000
std       21.5300
min        5.0000
25%       40.0000
50%       61.0000
75%       75.0000
max      100.0000
Name: Churn Score, dtype: float64

## Phase 6 — Dataset 4: OpenCelliD Cell Towers (410.csv)

In [36]:
# ── Load (no header — OpenCelliD format) ─────────────────────
CELLTOWER_COLS = [
    'radio', 'mcc', 'net', 'area', 'cell', 'unit',
    'lon', 'lat', 'range', 'samples', 'changeable',
    'created', 'updated', 'averageSignal'
]
cell_df = pd.read_csv(r'D:\telecom-customer-analytics-platform\data\raw\410.csv',
                      header=None, names=CELLTOWER_COLS)
print('410.csv (Cell Towers) loaded. Shape:', cell_df.shape)
cell_df.head()

410.csv (Cell Towers) loaded. Shape: (4225, 14)

,radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
0,GSM,410,3,52203,32307,0,71.5061,33.5514,1000,8,1,1387347609,1763025241,0
1,GSM,410,6,443,3433,0,71.4251,33.9551,1452,11,1,1399784437,1749770281,0
2,GSM,410,3,52204,32133,0,71.4274,33.9509,1000,10,1,1420720710,1750628043,0
3,GSM,410,6,280,62313,0,68.3961,28.2884,3523,6,1,1445849090,1753434062,0
4,LTE,410,4,32,11011,0,67.1172,24.9297,1000,3,1,1446762871,1748984582,0

In [37]:
# ── Dataset-Specific Notes ────────────────────────────────────
# • OpenCelliD format — no header row in file
# • mcc=410 → Pakistan; 'radio' is GSM/LTE/UMTS/NR
# • 'created' / 'updated' are Unix timestamps
# • 'averageSignal' is typically 0 (not reported) for most entries
# • 'cell' is the cell tower ID — high cardinality
# • Outlier detection meaningful for: range, samples, lat, lon

# Convert Unix timestamps for readability
cell_df['created_dt'] = pd.to_datetime(cell_df['created'], unit='s', errors='coerce')
cell_df['updated_dt'] = pd.to_datetime(cell_df['updated'], unit='s', errors='coerce')
print('Timestamp columns added.')

cell_result = run_full_profile(
    df                 = cell_df,
    name               = 'CellTowers_410',
    id_col             = None,   # composite key: mcc+net+area+cell
    force_numeric_cols = ['lat', 'lon', 'range', 'samples', 'averageSignal'],
    dataset_color      = PALETTE[4],   # orange
    corr_cmap          = 'Oranges'
)

Timestamp columns added.

██████████████████████████████████████████████████████████████████████
  PROFILING START : CellTowers_410
██████████████████████████████████████████████████████████████████████

============================================================
  DATASET OVERVIEW — CellTowers_410
============================================================
  Rows               : 4,225
  Columns            : 16
  Memory Usage (MB)  : 0.7258

============================================================
  COLUMN NAMES — CellTowers_410
============================================================
    1. radio
    2. mcc
    3. net
    4. area
    5. cell
    6. unit
    7. lon
    8. lat
    9. range
   10. samples
   11. changeable
   12. created
   13. updated
   14. averageSignal
   15. created_dt
   16. updated_dt

============================================================
  DATA TYPES — CellTowers_410
============================================================
       Column          DType
        radio         object
          mcc          int64
          net          int64
         area          int64
         cell          int64
         unit          int64
          lon        float64
          lat        float64
        range          int64
      samples          int64
   changeable          int64
      created          int64
      updated          int64
averageSignal          int64
   created_dt datetime64[ns]
   updated_dt datetime64[ns]

============================================================
  SUMMARY STATISTICS — CellTowers_410
============================================================

[Numeric]
            mcc       net       area           cell      unit       lon       lat      range   samples  changeable  \
count 4225.0000 4225.0000  4225.0000      4225.0000 4225.0000 4225.0000 4225.0000  4225.0000 4225.0000   4225.0000
mean   410.0000    3.7962 29460.7690  47985554.4256   12.3321   70.6565   29.9237  1546.9049    9.1725      1.0000
std      0.0000    6.2133 21244.5315  66824741.7187   59.7388    3.3655    3.2343  1865.2873   11.6523      0.0000
min    410.0000    1.0000     1.0000        97.0000   -1.0000   61.6143   24.7084   500.0000    1.0000      1.0000
25%    410.0000    1.0000 10305.0000   2413897.0000   -1.0000   67.1502   26.0491  1000.0000    1.0000      1.0000
50%    410.0000    3.0000 31017.0000  31596041.0000   -1.0000   71.5334   30.5569  1000.0000    4.0000      1.0000
75%    410.0000    4.0000 50265.0000  37138444.0000   -1.0000   73.1283   32.2630  1000.0000   11.0000      1.0000
max    410.0000   99.0000 65535.0000 268435455.0000  506.0000   74.8130   35.9135 27306.0000   51.0000      1.0000

              created         updated  averageSignal
count       4225.0000       4225.0000      4225.0000
mean  1744320655.1465 1760874430.2031         0.0000
std     54638378.9249   15122695.6430         0.0000
min   1387347609.0000 1735359899.0000         0.0000
25%   1743241765.0000 1746211261.0000         0.0000
50%   1757629155.0000 1763875743.0000         0.0000
75%   1771644336.0000 1772562542.0000         0.0000
max   1782290578.0000 1782311946.0000         0.0000

[Categorical]
       radio
count   4225
unique     3
top      LTE
freq    3409

============================================================
  DUPLICATE ANALYSIS — CellTowers_410
============================================================
  Duplicate Rows       : 0
  Duplicate Percentage : 0.00%

============================================================
  MISSING VALUES — CellTowers_410
============================================================
  No missing values found.

  Total Missing Cells  : 0
  Total Cells          : 67600

============================================================
  BLANK / WHITESPACE VALUES — CellTowers_410
============================================================
  No blank/whitespace values found.

============================================================
  UNIQUE VALUES — CellTowers_410
============================================================
       Column  Unique_Count  Total_Count  Unique_Pct
        radio             3         4225      0.0700
          mcc             1         4225      0.0200
          net            10         4225      0.2400
         area           459         4225     10.8600
         cell          4134         4225     97.8500
         unit           180         4225      4.2600
          lon          3027         4225     71.6400
          lat          3046         4225     72.0900
        range           850         4225     20.1200
      samples            51         4225      1.2100
   changeable             1         4225      0.0200
      created          3910         4225     92.5400
      updated          1465         4225     34.6700
averageSignal             1         4225      0.0200
   created_dt          3910         4225     92.5400
   updated_dt          1465         4225     34.6700

============================================================
  CARDINALITY — CellTowers_410
============================================================
       Column  Unique Cardinality
        radio       3         Low
          mcc       1         Low
          net      10      Medium
         area     459        High
         cell    4134        High
         unit     180        High
          lon    3027        High
          lat    3046        High
        range     850        High
      samples      51        High
   changeable       1         Low
      created    3910        High
      updated    1465        High
averageSignal       1         Low
   created_dt    3910        High
   updated_dt    1465        High

============================================================
  NUMERIC COLUMNS — CellTowers_410
============================================================
  mcc                            int64
  net                            int64
  area                           int64
  cell                           int64
  unit                           int64
  lon                            float64
  lat                            float64
  range                          int64
  samples                        int64
  changeable                     int64
  created                        int64
  updated                        int64
  averageSignal                  int64

  Total Numeric Columns : 13

============================================================
  OUTLIER DETECTION (IQR) — CellTowers_410
============================================================
  lat                          Q1=26.05  Q3=32.26  IQR=6.21  Bounds=[16.73, 41.58]  Outliers=0
  lon                          Q1=67.15  Q3=73.13  IQR=5.98  Bounds=[58.18, 82.10]  Outliers=0
  range                        Q1=1000.00  Q3=1000.00  IQR=0.00  Bounds=[1000.00, 1000.00]  Outliers=991
  samples                      Q1=1.00  Q3=11.00  IQR=10.00  Bounds=[-14.00, 26.00]  Outliers=379
  averageSignal                Q1=0.00  Q3=0.00  IQR=0.00  Bounds=[0.00, 0.00]  Outliers=0

  Boxplot saved → profiling_outputs\plots\CellTowers_410_boxplots.png

============================================================
  FREQUENCY DISTRIBUTION — CellTowers_410
============================================================

  [radio]
radio
LTE     3409
UMTS     415
GSM      401
  Bar chart saved → profiling_outputs\plots\CellTowers_410_freq_radio.png

============================================================
  CORRELATION MATRIX — CellTowers_410
============================================================
               mcc     net    area    cell    unit     lon     lat   range  samples  changeable  created  updated  averageSignal
mcc            NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      NaN         NaN      NaN      NaN            NaN
net            NaN  1.0000 -0.1990  0.1040  0.0160 -0.1140 -0.0620  0.0240   0.0720         NaN   0.0130  -0.0310            NaN
area           NaN -0.1990  1.0000 -0.2170 -0.0610  0.1830  0.1100 -0.0110  -0.0880         NaN   0.0930  -0.2060            NaN
cell           NaN  0.1040 -0.2170  1.0000 -0.1230  0.1270  0.1370 -0.0600   0.0410         NaN   0.2080   0.2240            NaN
unit           NaN  0.0160 -0.0610 -0.1230  1.0000 -0.1290 -0.1440  0.0310   0.0220         NaN  -0.0250  -0.1110            NaN
lon            NaN -0.1140  0.1830  0.1270 -0.1290  1.0000  0.8390 -0.1990  -0.2770         NaN   0.1330   0.2720            NaN
lat            NaN -0.0620  0.1100  0.1370 -0.1440  0.8390  1.0000 -0.1640  -0.1680         NaN   0.1400   0.4130            NaN
range          NaN  0.0240 -0.0110 -0.0600  0.0310 -0.1990 -0.1640  1.0000   0.3490         NaN  -0.2510  -0.0570            NaN
samples        NaN  0.0720 -0.0880  0.0410  0.0220 -0.2770 -0.1680  0.3490   1.0000         NaN  -0.2200   0.1280            NaN
changeable     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      NaN         NaN      NaN      NaN            NaN
created        NaN  0.0130  0.0930  0.2080 -0.0250  0.1330  0.1400 -0.2510  -0.2200         NaN   1.0000   0.2140            NaN
updated        NaN -0.0310 -0.2060  0.2240 -0.1110  0.2720  0.4130 -0.0570   0.1280         NaN   0.2140   1.0000            NaN
averageSignal  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN      NaN         NaN      NaN      NaN            NaN
  Heatmap saved → profiling_outputs\plots\CellTowers_410_correlation.png

============================================================
  MEMORY USAGE — CellTowers_410
============================================================
       Column  Bytes       KB
        radio 253915 247.9640
          lat  33800  33.0080
        range  33800  33.0080
   created_dt  33800  33.0080
averageSignal  33800  33.0080
      updated  33800  33.0080
      created  33800  33.0080
   changeable  33800  33.0080
      samples  33800  33.0080
   updated_dt  33800  33.0080
          lon  33800  33.0080
         unit  33800  33.0080
         cell  33800  33.0080
         area  33800  33.0080
          net  33800  33.0080
          mcc  33800  33.0080
        Index    132   0.1290

  TOTAL : 743.21 KB  (0.7258 MB)

  ✓ Profiling complete for [CellTowers_410]
██████████████████████████████████████████████████████████████████████

In [38]:
# ── Dataset-Specific: Radio Technology Breakdown ─────────────
print('='*60)
print('  RADIO TECHNOLOGY BREAKDOWN — CellTowers_410')
print('='*60)
radio_vc = cell_df['radio'].value_counts()
print(radio_vc)

# ── Network Operator (MNC) Distribution ──────────────────────
print('\n  MNC (Network Operator) Distribution:')
print(cell_df['net'].value_counts())

# ── AverageSignal filled vs zero ─────────────────────────────
sig_zero = (cell_df['averageSignal'] == 0).sum()
print(f'\n  averageSignal = 0 (unreported) : {sig_zero} / {len(cell_df)}  ({sig_zero/len(cell_df)*100:.1f}%)')

# ── Composite Key Duplicate Check ────────────────────────────
dup_key = cell_df.duplicated(subset=['mcc','net','area','cell']).sum()
print(f'\n  Composite Key (mcc+net+area+cell) Duplicates : {dup_key}')

============================================================
  RADIO TECHNOLOGY BREAKDOWN — CellTowers_410
============================================================
radio
LTE     3409
UMTS     415
GSM      401
Name: count, dtype: int64

  MNC (Network Operator) Distribution:
net
1     1300
4     1037
3      866
6      724
7      278
90       9
99       7
92       2
5        1
11       1
Name: count, dtype: int64

  averageSignal = 0 (unreported) : 4225 / 4225  (100.0%)

  Composite Key (mcc+net+area+cell) Duplicates : 5

## Phase 7 — Cross-Dataset Summary

In [39]:
# ============================================================
# CROSS-DATASET SUMMARY TABLE
# ============================================================

summary_rows = []
for ds_name, res in MASTER_RESULTS.items():
    ov  = res['overview']
    dup = res['duplicates']
    mv  = res['missing']
    total_missing = int(mv['Missing_Count'].sum())
    summary_rows.append({
        'Dataset':          ds_name,
        'Rows':             ov['rows'],
        'Columns':          ov['columns'],
        'Memory_MB':        ov['memory_mb'],
        'Duplicate_Rows':   dup['total_duplicate_rows'],
        'Duplicate_Pct':    dup['duplicate_pct'],
        'Total_Missing':    total_missing,
        'Cols_w_Missing':   int((mv['Missing_Count'] > 0).sum())
    })

cross_df = pd.DataFrame(summary_rows)
print('='*80)
print('  CROSS-DATASET SUMMARY')
print('='*80)
print(cross_df.to_string(index=False))

# Save to CSV
cross_df.to_csv(RESULTS_DIR / 'cross_dataset_summary.csv', index=False)
print('\n  Summary saved to results/cross_dataset_summary.csv')

================================================================================
  CROSS-DATASET SUMMARY
================================================================================
       Dataset  Rows  Columns  Memory_MB  Duplicate_Rows  Duplicate_Pct  Total_Missing  Cols_w_Missing
     PK_Cities   146        9     0.0489               0         0.0000            148               3
     Telco_CSV  7043       21     7.4196               0         0.0000             11               1
   Telco_Excel  7043       33    10.3374               0         0.0000           5185               2
CellTowers_410  4225       16     0.7258               0         0.0000              0               0

  Summary saved to results/cross_dataset_summary.csv

In [40]:
# ── Comparison Bar Chart ─────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(14, 5))
metrics = ['Rows', 'Duplicate_Rows', 'Total_Missing']
titles  = ['Row Count', 'Duplicate Rows', 'Total Missing Values']
colors  = [PALETTE[0], PALETTE[1], PALETTE[2]]

for ax, metric, title, clr in zip(axes, metrics, titles, colors):
    ax.bar(cross_df['Dataset'], cross_df[metric], color=clr, alpha=0.85)
    ax.set_title(title, fontsize=10)
    ax.set_xticklabels(cross_df['Dataset'], rotation=15, ha='right', fontsize=8)
    ax.set_ylabel('Count')

fig.suptitle('Cross-Dataset Comparison', fontsize=13, y=1.02)
plt.tight_layout()
path = PLOTS_DIR / 'cross_dataset_comparison.png'
plt.savefig(path, dpi=120, bbox_inches='tight')
plt.close()
print(f'Comparison chart saved → {path}')

Comparison chart saved → profiling_outputs\plots\cross_dataset_comparison.png

In [41]:
print('\nAll profiling complete. Plots and results saved to:', OUTPUT_DIR.resolve())
print('\nFiles generated:')
for f in sorted(OUTPUT_DIR.rglob('*')):
    if f.is_file():
        print(' ', f)

All profiling complete. Plots and results saved to: D:\telecom-customer-analytics-platform\notebooks\profiling_outputs

Files generated:
  profiling_outputs\plots\CellTowers_410_boxplots.png
  profiling_outputs\plots\CellTowers_410_correlation.png
  profiling_outputs\plots\CellTowers_410_freq_radio.png
  profiling_outputs\plots\cross_dataset_comparison.png
  profiling_outputs\plots\PK_Cities_boxplots.png
  profiling_outputs\plots\PK_Cities_correlation.png
  profiling_outputs\plots\PK_Cities_freq_country.png
  profiling_outputs\plots\Telco_CSV_boxplots.png
  profiling_outputs\plots\Telco_CSV_correlation.png
  profiling_outputs\plots\Telco_CSV_freq_gender.png
  profiling_outputs\plots\Telco_Excel_boxplots.png
  profiling_outputs\plots\Telco_Excel_correlation.png
  profiling_outputs\plots\Telco_Excel_freq_Country.png
  profiling_outputs\results\cross_dataset_summary.csv